
---

# computing cluster Comet
comet:

    # platform wide specs
    base_dir:       /cw3e/mead/projects/cnt107/nrt_hydro
    cores_per_node: 24
    modules:        'intel intelmpi netcdf'
    node_scratch:   ''
    
    forcing:
        # domains to subset after conus
        domains:    ['cnrfc', 'cbrfc']
        
    wrf_hydro:
        conus:
            partition: 'compute'
            nnodes:     4
            nprocs:    96
            minperday:  7
        cnrfc:
            partition: 'compute'
            nnodes:     1
            nprocs:    24
            minperday:  2
        cbrfc:
            partition: 'compute'
            nnodes:     1
            nprocs:    24
            minperday:  2
        
    obs:
        # products to process
        products:   ['modis']

# computing cluster Expanse
expanse:

    # platform wide specs
    base_dir:       /expanse/nfs/cw3e/cwp101/nrt_hydro
    cores_per_node: 128
    #modules:        'cpu/0.17.3b intel/19.1.3.304/6pv46so intel-mpi/2019.10.317/ezrfjne netcdf-fortran/4.5.3/vqnicf7'
    modules:        'slurm cpu/0.17.3b  gcc/10.2.0/npcyll4  openmpi/4.1.3/oq3qvsv netcdf-fortran/4.5.3/i35rncs'
    node_scratch:   'job_'
    
    forcing:
        # domains to subset after conus
        domains:    ['cnrfc', 'cbrfc']
        
    wrf_hydro:
        conus:
            partition: 'cw3e-compute'
            nnodes:     1
            nprocs:   128
            minperday:  5
        cnrfc:
            partition: 'cw3e-shared'
            nnodes:     0
            nprocs:    24
            minperday:  2
        cbrfc:
            partition: 'cw3e-shared'
            nnodes:     0
            nprocs:    24
            minperday:  2

    obs:
        # products to process
        products:   ['modis']

