---
# configuration for the system
#
# author: Ming Pan
# email: m3pan@ucsd.edu
# status: Development

# computing cluster Comet
comet:

    # platform wide specs
    base_dir:       /cw3e/mead/projects/cnt107/nrt_hydro
    cores_per_node: 24
    modules:        'intel intelmpi netcdf'
    node_scratch:   ''
    
    forcing:
        # domains to subset after conus
        domains:    ['cnrfc', 'cbrfc']
        
    wrf_hydro:
        conus:
            partition: 'compute'
            nnodes:     4
            nprocs:    96
            minperday:  7
        cnrfc:
            partition: 'compute'
            nnodes:     1
            nprocs:    24
            minperday:  2
        cbrfc:
            partition: 'compute'
            nnodes:     1
            nprocs:    24
            minperday:  2
        
    obs:
        # products to process
        products:   ['modis']

# computing cluster Expanse
expanse:

    # platform wide specs
    base_dir:       /expanse/nfs/cw3e/cwp101/nrt_hydro
    cores_per_node: 128
    #modules:        'cpu/0.17.3b intel/19.1.3.304/6pv46so intel-mpi/2019.10.317/ezrfjne netcdf-fortran/4.5.3/vqnicf7'
    modules:        'slurm cpu/0.17.3b  gcc/10.2.0/npcyll4  openmpi/4.1.3/oq3qvsv netcdf-fortran/4.5.3/i35rncs'
    node_scratch:   'job_'
    
    forcing:
        # domains to subset after conus
        domains:    ['cnrfc', 'cbrfc', 'basins24', 'yampa']
        # flag to produce daily forcing data for LSTM modeling
        lstm:       True
        
    wrf_hydro:
        conus:
            partition: 'cw3e-compute'
            nnodes:     1
            nprocs:   128
            minperday:  5
            lake:       True
            climrange:  [1979, 2023]
            lonlatbox:  [-125, -67, 25, 50]
            mapdpi:   200
        cnrfc:
            partition: 'cw3e-shared'
            nnodes:     1
            nprocs:    32
            minperday:  2
            lake:       True
            climrange:  [1979, 2023]
            lonlatbox:  [-125, -113, 32, 44]
            mapdpi:    50
        cbrfc:
            partition: 'cw3e-shared'
            nnodes:     1
            nprocs:    64
            minperday:  2
            lake:       True
            climrange:  [1979, 2023]
            lonlatbox:  [-119, -103, 29, 45]
            mapdpi:    80
        basins24:
            partition: 'cw3e-shared'
            nnodes:     1
            nprocs:    16
            minperday:  2.5
            lake:       False
            climrange:  [1979, 2023]
            lonlatbox:  [-124, -117, 35, 42]
            mapdpi:    80
            lstm:
                TEST_PARA:
                    Ttrain:       ['19791001', '20190930']
                    Tvalid:       ['20210801', '20250731']
                    Tpredc:       ['20210801', '20250731']  # Forecast period
                    dyn_var_list: ['PREC', 'T2D', 'SWDOWN', 'LWDOWN', 'SMTOT', 'SWE', 'Qsim'] ## variables used as predictors
                    target_var:   ['FNF']
                    log_var_list: ['FNF', 'prec', 'Qsim', 'p_mean']  ## p and flow need log-transform
                    stc_var_list: ['elev', 'sand', 'slope', 'size', 'p_mean']
                HYPER_PARA:
                    nepoch:       400
                    batch_size:    24
                    rho:           48
                    hidden_size:   64
                    EPOCHsave:      5   # save model for every save step
        yampa:
            partition: 'cw3e-shared'
            nnodes:     1
            nprocs:    16
            minperday:  2.5
            lake:       False
            climrange:  [1979, 2023]
            lonlatbox:  [-112, -106, 39, 44]
            mapdpi:    80
    obs:
        # products to process
        products:   ['modis']

